"""update

Revision ID: f230438dc44d
Revises: 3771a05e2f6f
Create Date: 2025-11-09 15:48:58.979461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f230438dc44d'
down_revision: Union[str, Sequence[str], None] = '3771a05e2f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gdpr_accepted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datapoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('datapoint')
    op.drop_table('subject')
    op.drop_table('experiment')
    op.drop_constraint(None, 'subject_experiment_link', type_='foreignkey')
    op.drop_constraint(None, 'subject_experiment_link', type_='foreignkey')
    op.create_foreign_key(None, 'subject_experiment_link', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'subject_experiment_link', 'experiments', ['experiment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_experiment_link', type_='foreignkey')
    op.drop_constraint(None, 'subject_experiment_link', type_='foreignkey')
    op.create_foreign_key(None, 'subject_experiment_link', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'subject_experiment_link', 'experiment', ['experiment_id'], ['id'])
    op.create_table('experiment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('finished', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gdpr_accepted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datapoint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('real_value', sa.FLOAT(), nullable=False),
    sa.Column('target_value', sa.FLOAT(), nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('datapoints')
    op.drop_table('subjects')
    op.drop_table('experiments')
    # ### end Alembic commands ###
